import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerWithWitness } from "../witness.ts";
import { GetTextingVoiceShape, ListVoiceProfilesShape } from "../schema.ts";
import { getVoiceProfile, listVoiceProfiles } from "../storage/voice.ts";
import { errorResult, jsonResult } from "./_result.ts";

export function registerVoiceTools(server: McpServer): void {
  const listTool = {
      title: "List local aggregate texting style profiles",
      description:
        "List aggregate texting style profiles generated by the Messages for AI app under " +
        "~/.messages-mcp/voice. These profiles contain counts, ratios, and safe tokens only — " +
        "no raw message bodies.",
      inputSchema: ListVoiceProfilesShape,
      annotations: {
        title: "List texting style profiles",
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    } as const;
  const listHandler = async () => {
    try {
      return jsonResult({ profiles: listVoiceProfiles() });
    } catch (e) {
      return errorResult(`list_voice_profiles failed: ${(e as Error).message}`);
    }
  };

  registerWithWitness(server, "list_voice_profiles", listTool, listHandler);
  registerWithWitness(server, "list_texting_style_profiles", listTool, listHandler);

  const getTool = {
      title: "Get a local aggregate texting style profile",
      description:
        "Read a generated texting style guide and fingerprint. Defaults to profile='base'. " +
        "Use this as style guidance when drafting, then stage drafts for human approval. " +
        "The profile is aggregate-only and should not contain raw message bodies.",
      inputSchema: GetTextingVoiceShape,
      annotations: {
        title: "Get texting style",
        readOnlyHint: true,
        destructiveHint: false,
        idempotentHint: true,
        openWorldHint: false,
      },
    } as const;
  const getHandler = async (args: { profile: string }) => {
    try {
      const profile = getVoiceProfile(args.profile);
      if (profile.voice_md == null && profile.fingerprint == null) {
        return errorResult(
          `texting style profile '${args.profile}' has not been generated yet. Open Messages for AI and click Build Style.`
        );
      }
      return jsonResult(profile);
    } catch (e) {
      return errorResult(`get_texting_style failed: ${(e as Error).message}`);
    }
  };

  registerWithWitness(server, "get_texting_voice", getTool, getHandler);
  registerWithWitness(server, "get_texting_style", getTool, getHandler);
}
