import SwiftUI
import AppKit

/// Labs › Texting Wrapped. The full-bleed story IS the surface: a Wrapped
/// generated by a previous run is restored from disk and shown immediately;
/// otherwise the same full-bleed frame holds a single sunrise "cover card"
/// with one Generate button (and the in-card progress state). There is no
/// intermediate setup screen. Generate spawns the bundled `wrapped-generator`
/// Mach-O via `WrappedGeneratorController` — deterministic, on-device, no
/// network. The premium "Deep Read" panel (DeepReadController) rides below
/// the story and is the only part that talks to a model.
///
/// THEME (lab exception surface): everything here is dressed in the Wrapped
/// "sunrise" story system — warm editorial gradients, serif hero type, soft
/// grain, monospaced kickers — mirroring skills/texting-analytics/wrapped/
/// treatments.jsx rather than DS. The `Sunrise*` kit below is file-private
/// and must not leak outside this file.
struct WrappedToolView: View {
  enum PreviewToolbarPlacement: Equatable {
    case hidden
    case dedicatedTopRow
  }

  /// Persisted so a restored Wrapped keeps the last names choice.
  @AppStorage("wrapped.includeNames") private var includeNames = true
  /// Whether the view is parked on the Deep Read strip (vs the story). The
  /// toolbar button is the ONLY way down there — the story webview eats
  /// every wheel event, so free scrolling can never reach below the fold.
  @State private var showingDeepRead = false

  private enum WrappedScrollAnchor: Hashable {
    case story
    case deepRead
  }
  @StateObject private var generator = WrappedGeneratorController()
  @StateObject private var previewController = WrappedPreviewController()
  @StateObject private var deepRead = DeepReadController()
  private let exportController = WrappedPreviewExportController()
  @EnvironmentObject private var settings: SettingsStore
  @EnvironmentObject private var featureFlags: FeatureFlagStore
  @EnvironmentObject private var aiUsageLedger: AIUsageLedger
  @Environment(\.openWindow) private var openWindow
  @Environment(\.colorScheme) private var colorScheme

  /// Flag-gated (wrapped-deep-read): when off, the Deep Read toolbar button
  /// and the panel below the fold must not exist at all — not just disabled.
  private var deepReadEnabled: Bool {
    featureFlags.resolved(.wrappedDeepRead)
  }

  var body: some View {
    Group {
      if case .done(let experience) = generator.state {
        generatedPreview(experience)
      } else {
        lobby
      }
    }
    .onAppear {
      deepRead.usageLedger = aiUsageLedger
      generator.restoreExistingIfIdle(includeNames: includeNames)
    }
    // A flag flip mid-session must not leave the view parked on a strip
    // that no longer exists.
    .onChange(of: deepReadEnabled) { _, enabled in
      if !enabled { showingDeepRead = false }
    }
  }

  // MARK: - Full-bleed story (generated or restored)

  private func generatedPreview(_ experience: WrappedGeneratedExperience) -> some View {
    VStack(spacing: 0) {
      previewToolbar(experience)

      // The story gets EXACTLY one viewport (GeometryReader-sized) and the
      // Deep Read strip rides below the fold inside the scroll. The outer
      // ScrollView is load-bearing: the main window uses
      // .windowResizability(.contentSize), so any unbounded ideal height
      // here (the webview reporting the page's full height, or a tall
      // insights panel) balloons the WHOLE window layout past the screen —
      // sidebar and toolbar land offscreen and the visible window shows an
      // empty middle slice (the "deeply broken" P0). A ScrollView's ideal
      // stays small no matter how tall its content is.
      GeometryReader { proxy in
        ScrollViewReader { scroller in
          ScrollView {
            VStack(spacing: 0) {
              WrappedHTMLPreview(
                experience: experience,
                exportController: exportController,
                previewController: previewController
              ) { action in
                AnalyticsClient.shared.safeCapture(.wrappedPreviewInteraction, properties: [
                  .lab: .string(AnalyticsLab.wrapped.rawValue),
                  .action: .string(action.rawValue)
                ])
              }
              .frame(width: proxy.size.width, height: proxy.size.height)
              .id(WrappedScrollAnchor.story)

              if deepReadEnabled {
                WrappedDeepReadPanel(controller: deepRead)
                  .frame(width: proxy.size.width)
                  .id(WrappedScrollAnchor.deepRead)
              }
            }
          }
          // The webview swallows every wheel event over it, and it spans the
          // whole viewport — without an explicit control the Deep Read strip
          // below the fold is unreachable. The toolbar button drives this.
          .onChange(of: showingDeepRead) { _, wantsDeepRead in
            withAnimation(.easeInOut(duration: 0.3)) {
              scroller.scrollTo(
                wantsDeepRead ? WrappedScrollAnchor.deepRead : WrappedScrollAnchor.story,
                anchor: .top
              )
            }
          }
        }
      }
    }
    .frame(maxWidth: .infinity, maxHeight: .infinity)
    .background(Color.black)
  }

  private func previewToolbar(_ experience: WrappedGeneratedExperience) -> some View {
    HStack(spacing: 8) {
      previewButton(.exit, systemImage: "xmark") {
        generator.reset()
      }

      previewButton(.shareCard, systemImage: "square.and.arrow.up", prominent: true) {
        Task { await previewController.shareCurrentCard(using: exportController) }
      }
      .disabled(!previewController.status.isIdle)

      previewButton(.exportPNG, systemImage: "arrow.down.to.line", prominent: true) {
        Task { await previewController.exportCurrentCard(using: exportController) }
      }
      .disabled(!previewController.status.isIdle)

      previewButton(.revealInFinder, systemImage: "folder") {
        NSWorkspace.shared.activateFileViewerSelecting([experience.url])
      }

      previewButton(.openInBrowser, systemImage: "safari") {
        NSWorkspace.shared.open(experience.url)
      }

      if deepReadEnabled {
        Button {
          showingDeepRead.toggle()
        } label: {
          Label(showingDeepRead ? "Back to story" : "Deep Read", systemImage: showingDeepRead ? "chevron.up" : "sparkles")
            .labelStyle(.titleAndIcon)
            .lineLimit(1)
        }
        .buttonStyle(SunriseToolbarButtonStyle(prominent: true))
        .help(showingDeepRead ? "Back to the story" : "AI insights: voice signature, ghosting, vibe, severance")
        .accessibilityLabel(showingDeepRead ? "Back to story" : "Deep Read insights")
      }

      if settings.isTextingWrappedOnly {
        Button("Continue setup") {
          openWindow(id: WindowID.onboarding)
        }
        .buttonStyle(SunriseToolbarButtonStyle(prominent: true))
      }

      if let status = previewController.status.text {
        Text(status)
          .font(.system(size: 11, weight: .heavy))
          .foregroundStyle(statusColor)
          .lineLimit(1)
          .padding(.leading, 8)
          .transition(.opacity)
      }

      Spacer(minLength: 0)
    }
    .padding(.horizontal, 16)
    .padding(.vertical, 10)
    .frame(maxWidth: .infinity, alignment: .leading)
    .background(Color.black)
  }

  @ViewBuilder
  private func previewButton(
    _ action: WrappedPreviewNativeAction,
    systemImage: String,
    prominent: Bool = false,
    perform: @escaping () -> Void
  ) -> some View {
    Button(action: perform) {
      Label(action.title, systemImage: systemImage)
        .labelStyle(.titleAndIcon)
        .lineLimit(1)
    }
    .buttonStyle(SunriseToolbarButtonStyle(prominent: prominent))
    .help(action.title)
    .accessibilityLabel(action.title)
  }

  private var statusColor: Color {
    switch previewController.status {
    case .failed:
      return Color(red: 1.0, green: 0.46, blue: 0.52)
    case .success:
      return Color(red: 0.58, green: 1.0, blue: 0.72)
    case .working:
      return .white.opacity(0.82)
    case .idle:
      return .white.opacity(0.56)
    }
  }

  // MARK: - Test seams (placement contract shared with WrappedPreviewTests)

  private var isGenerating: Bool {
    if case .generating = generator.state { return true }
    return false
  }

  static func usesFocusedPreview(for state: WrappedGeneratorController.State) -> Bool {
    if case .done = state { return true }
    return false
  }

  static func previewToolbarPlacement(for state: WrappedGeneratorController.State) -> PreviewToolbarPlacement {
    usesFocusedPreview(for: state) ? .dedicatedTopRow : .hidden
  }

  static var previewToolbarActions: [WrappedPreviewNativeAction] {
    [.exit, .shareCard, .exportPNG, .revealInFinder, .openInBrowser]
  }

  // MARK: - Lobby (empty / generating / failed — still the full-bleed frame)

  private var lobby: some View {
    ScrollView {
      VStack(spacing: 18) {
        coverCard
          .fullDiskAccessGate(toolName: "Texting Wrapped")
        if case .failed(let reason, let fdaMissing) = generator.state {
          failureCard(reason: reason, fdaMissing: fdaMissing)
        }
        if settings.isTextingWrappedOnly {
          Button("Continue setup") {
            openWindow(id: WindowID.onboarding)
          }
          .buttonStyle(SunriseToolbarButtonStyle(prominent: false))
        }
      }
      .padding(.vertical, 40)
      .padding(.horizontal, 28)
      .frame(maxWidth: .infinity)
    }
    .frame(maxWidth: .infinity, maxHeight: .infinity)
    .background(Color.black)
  }

  /// The cover card of the story, doubling as the generate control.
  private var coverCard: some View {
    ZStack {
      SunrisePalette.gradient
      SunriseGrain()
      VStack(alignment: .leading, spacing: 14) {
        Text("texting wrapped · textingwrapped.com")
          .font(.system(size: 8, weight: .medium, design: .monospaced))
          .tracking(1.2)
          .textCase(.uppercase)
          .foregroundStyle(SunrisePalette.soft.opacity(0.72))

        Text("00 · cover")
          .font(.system(size: 9, weight: .semibold, design: .monospaced))
          .tracking(0.9)
          .textCase(.uppercase)
          .foregroundStyle(SunrisePalette.soft)

        Text("Your year\nin texts.")
          .font(.system(size: 42, weight: .regular, design: .serif).italic())
          .lineSpacing(2)
          .foregroundStyle(SunrisePalette.ink)
          .accessibilityLabel("Your year in texts")

        Text("Reply speed, your inner circle, group-chat presence, a playful texting age, your archetype — a swipeable story with a past-year and all-time toggle built in. Generated on-device; nothing leaves your Mac.")
          .font(.system(size: 12, weight: .semibold))
          .lineSpacing(2.5)
          .foregroundStyle(SunrisePalette.ink.opacity(0.78))
          .fixedSize(horizontal: false, vertical: true)

        sampleMetric

        SunriseCheckbox(
          title: "Include contact names",
          subtitle: "Turn off for a version safe to share publicly.",
          isOn: $includeNames
        )
        .disabled(isGenerating)

        generateControl

        Text("generated on-device · nothing leaves your mac")
          .font(.system(size: 8, weight: .semibold, design: .monospaced))
          .tracking(0.9)
          .textCase(.uppercase)
          .foregroundStyle(SunrisePalette.soft)
      }
      .padding(26)
    }
    .frame(maxWidth: 430, alignment: .leading)
    .fixedSize(horizontal: false, vertical: true)
    .clipShape(RoundedRectangle(cornerRadius: 18, style: .continuous))
    .overlay(
      RoundedRectangle(cornerRadius: 18, style: .continuous)
        .strokeBorder(Color.white.opacity(0.14), lineWidth: 1)
    )
    .shadow(color: Color.black.opacity(0.55), radius: 18, y: 10)
  }

  /// Dummy metric so the empty frame previews the story's look.
  private var sampleMetric: some View {
    VStack(alignment: .leading, spacing: 6) {
      Text("Half your replies land within")
        .font(.system(size: 8.5, weight: .medium, design: .monospaced))
        .tracking(0.5)
        .textCase(.uppercase)
        .foregroundStyle(SunrisePalette.soft)
      HStack(alignment: .firstTextBaseline, spacing: 4) {
        Text("4.2")
          .font(.system(size: 34, weight: .regular, design: .serif).italic())
        Text("min")
          .font(.system(size: 14, weight: .regular, design: .serif).italic())
        Spacer(minLength: 8)
        Text("sample card — yours is built\nfrom your real history")
          .font(.system(size: 7.5, weight: .medium, design: .monospaced))
          .tracking(0.4)
          .textCase(.uppercase)
          .multilineTextAlignment(.trailing)
          .foregroundStyle(SunrisePalette.soft.opacity(0.85))
      }
      .foregroundStyle(SunrisePalette.ink)
    }
    .padding(.vertical, 4)
    .opacity(0.82)
    .accessibilityLabel("Sample story metric with dummy data")
  }

  @ViewBuilder
  private var generateControl: some View {
    if isGenerating {
      HStack(spacing: 10) {
        ProgressView()
          .controlSize(.small)
          .environment(\.colorScheme, .dark) // spinner must read on the ink pill
        Text("Reading your year. This is the part where you wait.")
          .font(.system(size: 12, weight: .heavy))
          .foregroundStyle(.white)
          .lineLimit(1)
          .minimumScaleFactor(0.8)
      }
      .padding(.horizontal, 18)
      .frame(height: 40)
      .frame(maxWidth: .infinity)
      .background(Capsule().fill(SunrisePalette.ink))
      .transition(.opacity)
      .accessibilityLabel("Generating")
    } else {
      Button {
        generator.generate(includeNames: includeNames)
      } label: {
        Text("Generate my Wrapped.")
          .font(.system(size: 13.5, weight: .heavy))
          .foregroundStyle(.white)
          .frame(height: 40)
          .frame(maxWidth: .infinity)
      }
      .buttonStyle(SunrisePillButtonStyle())
      .accessibilityLabel("Generate")
    }
  }

  private func failureCard(reason: String, fdaMissing: Bool) -> some View {
    VStack(alignment: .leading, spacing: 10) {
      Text("Well. That didn't work.")
        .font(.system(size: 16, weight: .regular, design: .serif).italic())
        .foregroundStyle(.white)
      HStack(alignment: .firstTextBaseline, spacing: 8) {
        // Severity keeps its non-color signal (the triangle) and its color.
        Image(systemName: "exclamationmark.triangle.fill").foregroundStyle(.orange)
        Text(reason)
          .font(.system(size: 12, weight: .semibold))
          .foregroundStyle(.white.opacity(0.82))
          .fixedSize(horizontal: false, vertical: true)
      }
      if fdaMissing {
        Button("Open Full Disk Access settings") {
          if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles") {
            NSWorkspace.shared.open(url)
          }
        }
        .buttonStyle(SunriseToolbarButtonStyle(prominent: true))
      }
    }
    .padding(18)
    .frame(maxWidth: 430, alignment: .leading)
    .background(
      RoundedRectangle(cornerRadius: 14, style: .continuous)
        .fill(SunrisePalette.panel)
    )
    .overlay(
      RoundedRectangle(cornerRadius: 14, style: .continuous)
        .strokeBorder(Color.white.opacity(0.14), lineWidth: 1)
    )
  }
}

// MARK: - File-private sunrise kit (do not export; panel has its own copy)

private enum SunrisePalette {
  /// Story-card ink — deep plum, constant across schemes (the card carries
  /// the contrast, same rule as the generated HTML).
  static let ink = Color(red: 0.10, green: 0.04, blue: 0.08)
  static let soft = Color(red: 0.23, green: 0.06, blue: 0.13).opacity(0.78)
  /// Dark panel surface used off-card (failure card).
  static let panel = Color(red: 0.11, green: 0.05, blue: 0.09)

  static let gradient = LinearGradient(
    colors: [
      Color(red: 1.0, green: 0.70, blue: 0.48),
      Color(red: 1.0, green: 0.37, blue: 0.23),
      Color(red: 0.70, green: 0.11, blue: 0.30)
    ],
    startPoint: .top,
    endPoint: .bottomTrailing
  )
}

/// The story system's paper grain — dot lattice with deterministic jitter.
private struct SunriseGrain: View {
  var body: some View {
    GeometryReader { proxy in
      Canvas { context, size in
        let spacing: CGFloat = 15
        let opacity = 0.055
        for y in stride(from: CGFloat(0), through: size.height, by: spacing) {
          for x in stride(from: CGFloat(0), through: size.width, by: spacing) {
            let jitter = CGFloat((Int(x + y) % 5) - 2)
            var path = Path()
            path.addEllipse(in: CGRect(x: x + jitter, y: y - jitter, width: 1.2, height: 1.2))
            context.fill(path, with: .color(.black.opacity(opacity)))
          }
        }
      }
      .frame(width: proxy.size.width, height: proxy.size.height)
    }
    .allowsHitTesting(false)
  }
}

/// Compact buttons for the black toolbar row: white pill = prominent, black
/// with a white edge = secondary. Press = tiny depress (suppressed under
/// Reduce Motion).
private struct SunriseToolbarButtonStyle: ButtonStyle {
  var prominent = false
  @Environment(\.accessibilityReduceMotion) private var reduceMotion
  @Environment(\.isEnabled) private var isEnabled

  func makeBody(configuration: Configuration) -> some View {
    let pressed = configuration.isPressed
    return configuration.label
      .font(.system(size: 11, weight: .heavy))
      .lineLimit(1)
      .padding(.horizontal, prominent ? 14 : 12)
      .frame(height: 28)
      .foregroundStyle(prominent ? Color.black : Color.white)
      .background(
        RoundedRectangle(cornerRadius: 8, style: .continuous)
          .fill(prominent ? Color.white : Color(red: 0.063, green: 0.063, blue: 0.075))
      )
      .overlay(
        RoundedRectangle(cornerRadius: 8, style: .continuous)
          .strokeBorder(Color.white.opacity(prominent ? 0 : 0.32), lineWidth: 1.5)
      )
      .offset(y: pressed ? 1 : 0)
      .opacity(isEnabled ? (pressed ? 0.92 : 1) : 0.45)
      .animation(reduceMotion ? nil : .easeOut(duration: 0.1), value: pressed)
  }
}

/// The one prominent action on the cover card — ink pill on the gradient.
private struct SunrisePillButtonStyle: ButtonStyle {
  @Environment(\.accessibilityReduceMotion) private var reduceMotion
  @Environment(\.isEnabled) private var isEnabled

  func makeBody(configuration: Configuration) -> some View {
    let pressed = configuration.isPressed
    return configuration.label
      .background(Capsule().fill(SunrisePalette.ink))
      .overlay(Capsule().strokeBorder(Color.white.opacity(0.18), lineWidth: 1))
      .shadow(color: Color.black.opacity(pressed ? 0.15 : 0.35), radius: pressed ? 2 : 7, y: pressed ? 1 : 4)
      .offset(y: pressed ? 1 : 0)
      .opacity(isEnabled ? 1 : 0.55)
      .animation(reduceMotion ? nil : .easeOut(duration: 0.1), value: pressed)
  }
}

/// Checkbox with the DSCheckbox accessibility contract (label + On/Off
/// value), drawn in story ink for the gradient card.
private struct SunriseCheckbox: View {
  let title: String
  let subtitle: String?
  @Binding var isOn: Bool
  @Environment(\.accessibilityReduceMotion) private var reduceMotion

  var body: some View {
    Button {
      withAnimation(DS.motion(reduceMotion, .easeInOut(duration: 0.14))) {
        isOn.toggle()
      }
    } label: {
      HStack(alignment: .top, spacing: 10) {
        ZStack {
          RoundedRectangle(cornerRadius: 4, style: .continuous)
            .fill(isOn ? SunrisePalette.ink : Color.white.opacity(0.35))
            .frame(width: 18, height: 18)
            .overlay(
              RoundedRectangle(cornerRadius: 4, style: .continuous)
                .strokeBorder(SunrisePalette.ink.opacity(isOn ? 1 : 0.6), lineWidth: 1.5)
            )
          if isOn {
            Image(systemName: "checkmark")
              .font(.system(size: 10, weight: .black))
              .foregroundStyle(.white)
          }
        }
        .padding(.top, 1)

        VStack(alignment: .leading, spacing: 2) {
          Text(title)
            .font(.system(size: 12, weight: .heavy))
            .foregroundStyle(SunrisePalette.ink)
          if let subtitle {
            Text(subtitle)
              .font(.system(size: 10.5, weight: .medium))
              .foregroundStyle(SunrisePalette.ink.opacity(0.62))
              .fixedSize(horizontal: false, vertical: true)
          }
        }
        Spacer(minLength: 0)
      }
      .contentShape(Rectangle())
    }
    .buttonStyle(.plain)
    .accessibilityLabel(title)
    .accessibilityValue(isOn ? "On" : "Off")
  }
}

// MARK: - First-open intro (registered in ToolRegistry)

extension WrappedToolView {
  /// Registry hook for the first-open intro sheet. The sunrise kit stays
  /// file-private; only an opaque AnyView crosses the file boundary.
  static func makeIntro(_ actions: LabIntroActions) -> AnyView {
    AnyView(WrappedIntroView(actions: actions))
  }
}

/// The intro is the cover card stretched to a landing page: same gradient,
/// grain, serif italic hero, mono kickers, and the Generate-style ink pill.
private struct WrappedIntroView: View {
  let actions: LabIntroActions

  var body: some View {
    ZStack {
      SunrisePalette.gradient
      SunriseGrain()
      VStack(alignment: .leading, spacing: 0) {
        Text("texting wrapped · made for humans")
          .font(.system(size: 9, weight: .semibold, design: .monospaced))
          .tracking(1.2)
          .textCase(.uppercase)
          .foregroundStyle(SunrisePalette.soft)

        Text("Your year in texts,\ntold back to you.")
          .font(.system(size: 38, weight: .regular, design: .serif).italic())
          .lineSpacing(3)
          .foregroundStyle(SunrisePalette.ink)
          .accessibilityLabel("Your year in texts, told back to you")
          .padding(.top, 18)

        VStack(alignment: .leading, spacing: 14) {
          benefit("01", "How fast you actually reply — the honest number.")
          benefit("02", "Your inner circle, ranked by who really shows up.")
          benefit("03", "Your texting archetype, named to your face.")
        }
        .padding(.top, 28)

        Spacer(minLength: 18)

        Button {
          actions.onContinue()
        } label: {
          Text("Show me my year.")
            .font(.system(size: 13.5, weight: .heavy))
            .foregroundStyle(.white)
            .frame(height: 40)
            .frame(maxWidth: .infinity)
        }
        .buttonStyle(SunrisePillButtonStyle())
        .keyboardShortcut(.defaultAction)
        .accessibilityLabel("Continue to Texting Wrapped")

        Button {
          actions.onCancel()
        } label: {
          Text("Not now")
            .font(.system(size: 11.5, weight: .bold))
            .foregroundStyle(SunrisePalette.ink.opacity(0.65))
            .frame(height: 30)
            .frame(maxWidth: .infinity)
        }
        .buttonStyle(.plain)
        .accessibilityLabel("Not now")
        .padding(.top, 6)

        Text("generated on-device · nothing leaves your mac")
          .font(.system(size: 8, weight: .semibold, design: .monospaced))
          .tracking(0.9)
          .textCase(.uppercase)
          .foregroundStyle(SunrisePalette.soft)
          .frame(maxWidth: .infinity)
          .padding(.top, 14)
      }
      .padding(38)
    }
  }

  private func benefit(_ index: String, _ text: String) -> some View {
    HStack(alignment: .firstTextBaseline, spacing: 10) {
      Text(index)
        .font(.system(size: 9, weight: .semibold, design: .monospaced))
        .tracking(0.9)
        .foregroundStyle(SunrisePalette.soft)
      Text(text)
        .font(.system(size: 13, weight: .semibold))
        .lineSpacing(2)
        .foregroundStyle(SunrisePalette.ink.opacity(0.85))
        .fixedSize(horizontal: false, vertical: true)
    }
    .accessibilityElement(children: .combine)
  }
}
